#!/bin/bash
cd src
autopep8 $(find *.py | grep -v player | grep -v strategy) -i --max-line-length 256
pylint $(find *.py | grep -v player | grep -v strategy) --rcfile ../config/.pylintrc && \
pdoc3 $(find *.py | grep -v player | grep -v strategy) -f -o ../doc && \
git add ../doc